name: Docker Image CI

on:
  push:
    branches: [ "webhook" ]
  pull_request:
    branches: [ "webhook" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: glambert590/kan_bcc:1.0.0
          context: ./apps/web/